### ISSUE TITLE
Conocimientos

### ISSUE THREAD

**Issue by JFermepin** [pdepviernestm/2023-bienvenida-Lucssiano#1]
Luciano! Como estás?

Vi tu perfil y me gusto mucho como esta hecho tu portfolio, muy buen laburo. 

Me intriga, de donde aprendiste? Por que estaria necesitando algun que otro cursito, principalmente de Javascript 😅

Saludos

**Comment by Lucssiano** [comment]
Hola Jeronimo, muchas gracias!

Empecé en el secundario teniendo una introducción a HTML, CSS y Javascript en una materia llamada "Lenguajes Electrónicos".
Allí hicimos los cursos de Codeacademy (https://www.codecademy.com/learn) y proyectos que nos mandaba el profesor.

Desde ese momento me empezó a interesar en gran medida el mundo del Desarrollo Web, entonces empecé a estudiar de forma autodidacta por Youtube o Cursos de Udemy. 

Despues me metí en una comunidad de programación, donde aprendí un monton intercambiando charlas con los miembros.

En conclusión hice un poco de todo, despues los conocimientos de Javascript y TypeScript los consolide un poco más haciendo los dos primeros módulos de Apx (https://apx.school/). Igualmente me falta muchisimo por aprender y quiero seguir haciendolo.

Saludos!

**Comment by Lucssiano** [comment]
Te paso la comunidad que te mencione: https://discord.gg/sEAwzZbxzp

Esta muy buena, siempre que tengas una duda hay alguien para ayudarte y es un server muy copado
