### ISSUE TITLE
Front-end vs Back-end

### ISSUE THREAD

**Issue by Fran123445** [pdepviernestm/2023-bienvenida-Lucssiano#2]
Hola Luciano, quería saber que es lo que te hace decantarte por el desarrollo front-end por encima del back-end

**Comment by Lucssiano** [comment]
Hola Fran, me decante por el desarrollo front-end porque es lo primero que aprendí, no por algún motivo especial. A la larga me gustaria poder ser un desarrollador FullStack, sabiendo tanto tecnologias de front como de back, por el momento solo sé de front y tengo una idea nomás de back pero muy poco.

Saludos!
